apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EjiiZVGp0kd/5u2+DQAm7LGzYuUHFlgVweJYFyliJgi2rs07,iv:U+T3VpgWdfi/oBuePf4QclVBZF364ifqnRgEka4GJvk=,tag:PON5w3vaZRHTOI2fyPC7Rw==,type:str]
    credentials.json: ENC[AES256_GCM,data:0bxDqzfPvjc/IlVa4cjKl7MswPxZl4ikEHN87iypp1cZgmvv1oAr6/RDUS6OVn7fIqirzOSMMXoffsr5vxtqWTHEq2I+VIlQhdlSpCfV+3w0/4WgWVl7VLL/1fT36/F2ECbA7UFIPe5DK8LEOLQCGgprr2h1jzISuFLzfVjIRUeJsa/xlq9CDZsBa4YwBszWAowAK54/IVozdRXcOughuqJ9zwDruCsMVEPdaABhNQ==,iv:do0RmQEM6PmBaV5orikxyYY0sw/w+ukk9GYt0LVYd+A=,tag:ESLPUCJmuKZqZ234ie+vWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUFBkWXV5QThnaXYxUG1y
            YTZlbWJxVXV3OTdOT254ZFZRMHBROFdUOURjCms5Q3dSbEhHcEVOd2JXWkczajhr
            ZGZ5WlVKR1QyVkk1d2hSWkhid3FJVzQKLS0tIHd2NFkwdkpVSGs3T3RXZjc3dmV2
            eG1aalh4N0JJMlhtMmVwakJqdmpXNHcKmD9ZaKPj19Gf0KCWyjMHWKG4/s9J5J8e
            gnIPtdU5nld71MInkj7FUaPoNAMSs1S03QkXCmD54ZiVrCAg8TsWlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T22:33:00Z"
    mac: ENC[AES256_GCM,data:QDNABQ8hW24JtEFLpyR6r7DVPeiYI1dl1dDSoPPUtmbpamlJ9NUonOnAnIK3QmUlCid6fED3h/uvQBtpYvKayBINnDGu2vJt1El0YxHuWzxQ/0AZj4DkXhOl2qtLPOVm8+DhGxpkC5nvtCYSAiwwICnuHcY3XBXLDMVlw0ELAvI=,iv:i6Pdrn9qRpo9ANxeUjSJ+iYB5h0E2UfTGoQ8pB4QGeA=,tag:ACmfelMMqTMRYNOV6WnoKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
